### ISSUE TITLE
Multiple Users Google Album Archive URL

### ISSUE THREAD

**Issue by TheSarali** [ddo02/GooglePhotosDirectLink#1]
If you have multiple user accounts on Google and you're not signed into your main one the URL changes from "https://get.google.com/albumarchive" to "https://get.google.com/u/1/albumarchive/" and this causes the extension to no longer work.

Could this possibly be fixed?  Would be handy for those of us with multiple user accounts.

**Comment by ddo02** [comment]
Fixed!
I modified the filter URL to a more generic URL. Now, any URL started with "https://get.google.com/" will works.
